/**
 * API client placeholder (M0).
 *
 * The typed API client is GENERATED from the backend OpenAPI spec — it is not
 * hand-written here. See `api-client/README.md` and the `generate:api` npm
 * script, which runs `openapi-typescript` against the backend dev OpenAPI URL
 * (http://localhost:8080/openapi/v1.json) and emits `api-client/schema.ts`.
 *
 * Once the backend exists, a thin fetch wrapper (e.g. openapi-fetch) will live
 * here and consume those generated types. For M0 there are no real API calls.
 */

// Generated API types live in `@/api-client/schema` (paths / components / operations),
// regenerated by `npm run generate:api`. M0 has no documented endpoints yet, so the
// generated module is intentionally empty — import specific types here as the API grows.

export const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8080";
